[2023-09-19T13:32:52.724+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task __airflow_temporary_run_2023-09-19T07:47:48.039632+00:00__ [queued]>
[2023-09-19T13:32:52.729+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.load_to_postgres_task __airflow_temporary_run_2023-09-19T07:47:48.039632+00:00__ [queued]>
[2023-09-19T13:32:52.729+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:32:52.741+0545] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): load_to_postgres_task> on 2023-09-19 00:00:00+00:00
[2023-09-19T13:32:52.745+0545] {standard_task_runner.py:57} INFO - Started process 12637 to run task
[2023-09-19T13:32:52.749+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'load_to_postgres_task', '__airflow_temporary_run_2023-09-19T07:47:48.039632+00:00__', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmppuazimc4']
[2023-09-19T13:32:52.751+0545] {standard_task_runner.py:85} INFO - Job 88: Subtask load_to_postgres_task
[2023-09-19T13:32:52.791+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.load_to_postgres_task __airflow_temporary_run_2023-09-19T07:47:48.039632+00:00__ [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-19T13:32:52.843+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__airflow_temporary_run_2023-09-19T07:47:48.039632+00:00__'
[2023-09-19T13:32:52.844+0545] {sql.py:274} INFO - Executing: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;
[2023-09-19T13:32:52.848+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-19T13:32:52.896+0545] {base.py:73} INFO - Using connection ID '***_conn_1' for task execution.
[2023-09-19T13:32:52.916+0545] {sql.py:418} INFO - Running statement: COPY user_input_table FROM '/tmp/user_data.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2023-09-19T13:32:52.917+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/tmp/user_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-09-19T13:32:52.920+0545] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=project_dag, task_id=load_to_***_task, execution_date=20230919T000000, start_date=20230919T074752, end_date=20230919T074752
[2023-09-19T13:32:52.928+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task load_to_***_task (could not open file "/tmp/user_data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 12637)
[2023-09-19T13:32:52.960+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T13:32:52.973+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
