[2023-09-19T13:59:38.439+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:14:29.985035+00:00 [queued]>
[2023-09-19T13:59:38.444+0545] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:14:29.985035+00:00 [queued]>
[2023-09-19T13:59:38.444+0545] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-19T13:59:38.455+0545] {taskinstance.py:1380} INFO - Executing <Task(FileSensor): file_sensor_task> on 2023-09-19 08:14:29.985035+00:00
[2023-09-19T13:59:38.458+0545] {standard_task_runner.py:57} INFO - Started process 26215 to run task
[2023-09-19T13:59:38.460+0545] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'file_sensor_task', 'manual__2023-09-19T08:14:29.985035+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpouh1pz6w']
[2023-09-19T13:59:38.461+0545] {standard_task_runner.py:85} INFO - Job 100: Subtask file_sensor_task
[2023-09-19T13:59:38.482+0545] {task_command.py:415} INFO - Running <TaskInstance: project_dag.file_sensor_task manual__2023-09-19T08:14:29.985035+00:00 [running]> on host ubuntu-Lenovo-Legion-5-15ARH05
[2023-09-19T13:59:38.521+0545] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='project_dag' AIRFLOW_CTX_TASK_ID='file_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T08:14:29.985035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-19T08:14:29.985035+00:00'
[2023-09-19T13:59:38.525+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T13:59:38.525+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T14:00:08.555+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T14:00:08.555+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T14:00:38.587+0545] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-09-19T14:00:38.587+0545] {filesystem.py:64} INFO - Poking for file /tmp/user_data.csv
[2023-09-19T14:00:38.588+0545] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Airflow/venv_airflow/lib/python3.10/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.06522704299823 seconds exceeds the specified timeout of 40.0.
[2023-09-19T14:00:38.593+0545] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=project_dag, task_id=file_sensor_task, execution_date=20230919T081429, start_date=20230919T081438, end_date=20230919T081538
[2023-09-19T14:00:38.609+0545] {standard_task_runner.py:104} ERROR - Failed to execute job 100 for task file_sensor_task (Sensor has timed out; run duration of 60.06522704299823 seconds exceeds the specified timeout of 40.0.; 26215)
[2023-09-19T14:00:38.619+0545] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-19T14:00:38.650+0545] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
